// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin_gorm/config"
	"gin_gorm/controllers"
	"gin_gorm/core"
	"gin_gorm/middlewares"
	"gin_gorm/model"
	"gin_gorm/router"
)

// Injectors from wire.go:

func NewApp() *core.HServer {
	configConfig := config.NewConfig()
	db := config.NewMysql(configConfig)
	authModel := model.NewAuthModel(db)
	client := config.NewRedisClient(configConfig)
	authController := controllers.NewAuthController(authModel, client, configConfig)
	demoMiddleware := middlewares.NewDemoMiddleware(db)
	authRouter := router.NewAuthRouter(authController, demoMiddleware)
	engine := router.NewRouter(authRouter)
	hGrpcServer := core.NewHGrpcServer(configConfig)
	hGrpcClient := core.NewHGrpcClient(configConfig)
	hServer := core.NewHServer(engine, configConfig, hGrpcServer, hGrpcClient)
	return hServer
}
